= TLS Wizard

This is a GUI app to enable TLS for WildFly.

== How to run the application

Use this application to configure one-way TLS for applications deployed on WildFly. Two-way TLS is WIP.

.Prerequisites

. WildFly is installed.
. Maven is installed.

.Procedure

. Start the server.

. Navigate to the directory `tlswizard`.

. Launch this app with the command:
+
[source,options="nowrap"]
----
$ mvn clean javafx:run
----
+
This launches the TLS Wizard.

. Enter the IP for the server. The default is `127.0.0.1` (localhost). For local WildFly deployments, you don't need to update this.   

. Select `One-way TLS` or `Two-way TLS` to configure One-way TLS or Two-way TLS.

. Select `applications` or `management interfaces` to secure applications or management interfaces.

. Click *Next*.

** If you selected `One-way TLS`:
.. Enter a name for the key store to create with `.pkcs12` extension.
.. Enter details for the certificate to be generated. If you don't, all the values are set to `unknown`.
.. Click *Configure TLS*. 
.. To verify TLS, do this:

***  If you secure applications: Navigate to link:https://localhost:8443[]. Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered. 

*** If you secured the management interface: Navigate to link:http://localhost:9990[]. You will be redirected to `localhost:9993` Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered.

** That's it! one-way TLS is now enabled.

** If you selected `Two-way TLS`:
*** You are directed to a page with Work in Progress. You can click *Back* to go back to the home page.