= TLS Wizard

This is a GUI app to enable TLS for WildFly.

== How to run the application

Use this application to secure applications deployed to WildFly, or the WildFly management interface with one-way TLS by generating self-signed certificates.

.Prerequisites

. WildFly is installed.
. Maven is installed.

.Procedure

. Start a WildFly server.

. Navigate to the directory `tlswizard`.

. Launch this app with the command:
+
[source,options="nowrap"]
----
$ mvn clean javafx:run
----
+
This launches the TLS Wizard.

. Enter the IP for the server. The default is `127.0.0.1` (localhost). For local WildFly deployments, you don't need to update this.   

. Select `applications` or `management interfaces` to secure applications or management interfaces.

. Click *Next*.

. Enter a name for the key store to create with `.pkcs12` extension.
. Enter details for the certificate to be generated. If you don't, all the values are set to `unknown`.
. Click *Configure TLS*. 
. To verify TLS, do this:

***  If you secure applications: Navigate to link:https://localhost:8443[]. Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered. 

*** If you secured the management interface: Navigate to link:http://localhost:9990[]. You will be redirected to `localhost:9993` Inspect the certificate. The `Common Name (CN)` should match the first and last name you entered.

That's it! one-way TLS is now enabled.
